### ISSUE TITLE
Can't install because of unmet dependencies

### ISSUE THREAD

**Issue by cryoff** [aicodes/dashboard#3]
Unfortunately, I can't install dashboard on Ubuntu 16.04 because of:

UNMET PEER DEPENDENCY eslint-plugin-import@^1.13.0
├─┬ UNMET PEER DEPENDENCY eslint-plugin-import@2.2.0
and
npm ERR! electron-chromedriver@1.4.0 install: `node ./download-chromedriver.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.4.0 install script 'node ./download-chromedriver.js'.

NodeJS version: v4.2.6
npm version: 3.5.2

**Comment by xuy** [comment]
Thanks for reporting let me try to reproduce it on a virtual machine.

**Comment by xuy** [comment]
@cryoff hey I constructed this in the virtual machine. something is off about node. Anyways, it should fixed now with the latest commit -- I removed all eslint dependencies from package.json. 

The commit is 1ea667e. Re-ran `npm install` didn't give me the error. I will close it in a day if no further issues. Thanks!

-- Eric

**Comment by cryoff** [comment]
After some headbanging, I have got the updated versions of nodejs and npm:
> npm -v
3.10.9
> nodejs -v
v7.2.0

But the installation finished with this:
> npm install

> undefined postinstall /home/aandreychenko/Documents/sideSoftware/dashboard-master/dashboard
> install-app-deps

Installing app dependencies for arch x64 to /home/aandreychenko/Documents/sideSoftware/dashboard-master/dashboard/app

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.4.5 (node_modules/electron-builder/node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-osx@^1.0.0 (node_modules/7zip-bin/node_modules/7zip-bin-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-osx@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^1.0.0 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN dashboard No license field.

And trying to start:
> npm start

> @ start /home/aandreychenko/Documents/sideSoftware/dashboard-master/dashboard
> gulp start

fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/aandreychenko/Documents/sideSoftware/dashboard-master/dashboard/node_modules/electron/path.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (/home/aandreychenko/Documents/sideSoftware/dashboard-master/dashboard/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! @ start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script 'gulp start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.


Full log file is [here](https://expirebox.com/download/87517803d79d20495aa2264a06a706fa.html)

**Comment by xuy** [comment]
Hey @cryoff I think I might get a bit closer to the bottom of this.
I tried two approaches, both works.

Method 1: `rm node_modules/electron`, and then `npm install`. This apparently will reinstall electron.

Method 2: `cd node_modules/electron`, and then `node install.js`. 

I have no idea why there there is a race condition etc, but this will create the path.txt file that was missing.
